t1.o : t1.cpp
	g++ -o t1.o -std=c++11 -pthread -Wl,--no-as-needed t1.cpp

t2.o : t2.cpp
	g++ -o t2.o -std=c++11 -pthread -Wl,--no-as-needed t2.cpp

t3.o : t3.cpp
	g++ -o t3.o -std=c++11 -pthread -Wl,--no-as-needed t3.cpp

t4.o : t4.cpp
	g++ -o t4.o -std=c++11 -pthread -Wl,--no-as-needed t4.cpp

t5.o : t5.cpp
	g++ -o t5.o -std=c++11 -pthread -Wl,--no-as-needed t5.cpp
clean:
	rm *.o
